FROM python:alpine

# for run locally
#COPY aiqDocTests-1.4.0-py3-none-any.whl aiqDocTests-1.4.0-py3-none-any.whl
#RUN pip3 install aiqDocTests-1.4.0-py3-none-any.whl

RUN pip3 install aiqDocTests

WORKDIR aiqdoctests

COPY . .

COPY tests/.env.test docker/.env

COPY .aiqdoctests.config .aiqdoctests.config